[build]
    command = 'echo -e "\ngoogleAnalytics: $GOOGLE_ANALYTICS \ndisqusShortname: $DISQUS_SHORTNAME \n" >> hugo.yaml && hugo --gc --minify'
    functions = "netlify/functions"
    publish = "public"

[build.environment]
  HUGO_VERSION = "0.112.0"